language: node_js

node_js:
  - "9"

cache:
  directories:
    - ~/.npm
    - ~/.cache

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn build
  - yarn test

deploy:
  provider: heroku
  app: final-homework
  api_key:
    secure: $HEROKU_KEY
