language: node_js

node_js:
  - "9"

before_install:
 - export NODE_PATH=./src"

install:
  - yarn install

script:
  - yarn build
  - yarn test

deploy:
  provider: heroku
  app: final-homework
  api_key:
    secure: $HEROKU_KEY
